version: '3'
services:
  frontend:
    build: ./caria_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8800
      - NODE_ENV=production
    volumes:
      - ./caria_frontend/package.json:/app/package.json

  backend:
    build: ./caria_backend
    ports:
      - "8800:8800"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=PASS
    command: npm start
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=PASS
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data:

networks:
  default:
    driver: bridge